import React, { forwardRef } from "react";
import {
  Activity,
  AlertTriangle,
  ArrowRight,
  Bell,
  BookOpen,
  Bot,
  Box,
  Brain,
  Brush,
  Bug,
  Check,
  CheckCircle,
  CircleDot,
  Clock,
  ChartNoAxesCombined,
  ChartColumnIncreasing,
  ClipboardCheck,
  ClipboardPaste,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Copy,
  Crosshair,
  Cpu,
  Database,
  Diamond,
  Download,
  Eye,
  EyeOff,
  Filter,
  Flag,
  Film,
  Flame,
  Folder,
  FolderOpen,
  FolderKanban,
  Gauge,
  GalleryHorizontalEnd,
  Hexagon,
  History,
  Image as ImageIcon,
  Inbox,
  Info,
  Key,
  LayoutDashboard,
  LayoutGrid,
  Layers,
  Link as LinkIcon,
  List,
  ListStart,
  Loader2,
  Lock,
  LockOpen,
  LogOut,
  Mail,
  Menu,
  MessageSquareText,
  MessageCircle,
  Minus,
  Monitor,
  Moon,
  MoreVertical,
  MousePointer2,
  Move,
  Pause,
  PanelLeft,
  PanelRight,
  Pencil,
  PictureInPicture,
  PictureInPicture2,
  Play,
  Plus,
  RefreshCw,
  RotateCcw,
  Ruler,
  Save,
  Scan,
  Scissors,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  Sparkle,
  Sparkles,
  Spline,
  Square,
  SquareTerminal,
  Sun,
  Tag,
  Target,
  Trash2,
  Type,
  Upload,
  User,
  UserRoundCog,
  Users,
  Video,
  WandSparkles,
  X,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from "lucide-react";

import { cn } from "@/lib/utils";

import {
  AnnotationPolygon,
  AnnotationPolyline,
  Keypoints,
  MaskTrack,
  PolygonTrack,
  PolylineTrack,
  RotatedBox,
  SmartScribble,
} from "./annotationIcons";
import { useElementStyle } from "./useElementStyle";

/**
 * Stable icon adapter for Lucide and local annotation geometry.
 * Business surfaces consume their existing tool/navigation metadata so one meaning
 * keeps one icon across entry points. Generic actions may import Lucide directly.
 */
const ICON_MAP = {
  activity: Activity,
  "alert-triangle": AlertTriangle,
  arrowRight: ArrowRight,
  bell: Bell,
  // v0.10.13 · E1 · 标注指引图标
  book: BookOpen,
  bot: Bot,
  box: Box,
  brain: Brain,
  brush: Brush,
  annotationPolygon: AnnotationPolygon,
  annotationPolyline: AnnotationPolyline,
  keypoints: Keypoints,
  maskTrack: MaskTrack,
  polygonTrack: PolygonTrack,
  polylineTrack: PolylineTrack,
  rotatedBox: RotatedBox,
  smartScribble: SmartScribble,
  bug: Bug,
  check: Check,
  checkCircle: CheckCircle,
  circleDot: CircleDot,
  clock: Clock,
  chartAnalytics: ChartNoAxesCombined,
  chartPerformance: ChartColumnIncreasing,
  clipboardCheck: ClipboardCheck,
  clipboardPaste: ClipboardPaste,
  chevDown: ChevronDown,
  chevLeft: ChevronLeft,
  chevRight: ChevronRight,
  chevUp: ChevronUp,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  crosshair: Crosshair,
  cursor: MousePointer2,
  cube: Box,
  copy: Copy,
  cpu: Cpu,
  dashboard: LayoutDashboard,
  db: Database,
  diamond: Diamond,
  download: Download,
  edit: Pencil,
  eye: Eye,
  eyeOff: EyeOff,
  film: Film,
  filter: Filter,
  flag: Flag,
  flame: Flame,
  folder: Folder,
  folderOpen: FolderOpen,
  folderKanban: FolderKanban,
  gauge: Gauge,
  galleryHorizontalEnd: GalleryHorizontalEnd,
  grid: LayoutGrid,
  history: History,
  image: ImageIcon,
  inbox: Inbox,
  info: Info,
  key: Key,
  layers: Layers,
  link: LinkIcon,
  list: List,
  listStart: ListStart,
  loader2: Loader2,
  lock: Lock,
  unlock: LockOpen,
  logout: LogOut,
  mail: Mail,
  menu: Menu,
  messageSquareText: MessageSquareText,
  messageCircle: MessageCircle,
  minus: Minus,
  mm: SquareTerminal,
  monitor: Monitor,
  moon: Moon,
  more: MoreVertical,
  move: Move,
  panelLeft: PanelLeft,
  panelRight: PanelRight,
  pictureInPicture: PictureInPicture,
  pictureInPicture2: PictureInPicture2,
  pause: Pause,
  play: Play,
  plus: Plus,
  point: Crosshair,
  polygon: Hexagon,
  rect: Square,
  refresh: RefreshCw,
  "rotate-ccw": RotateCcw,
  ruler: Ruler,
  save: Save,
  scan: Scan,
  scissors: Scissors,
  search: Search,
  settings: Settings,
  shield: Shield,
  shieldAlert: ShieldAlert,
  sparkle: Sparkle,
  sparkles: Sparkles,
  spline: Spline,
  sun: Sun,
  tag: Tag,
  target: Target,
  trash: Trash2,
  type: Type,
  upload: Upload,
  user: User,
  userRoundCog: UserRoundCog,
  users: Users,
  video: Video,
  wandSparkles: WandSparkles,
  warning: AlertTriangle,
  x: X,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICON_MAP;

interface IconProps {
  name: IconName;
  size?: number;
  /** 与旧手写 SVG 接口一致：默认 1.6 */
  stroke?: number;
  style?: React.CSSProperties;
  className?: string;
}

export const Icon = forwardRef<SVGSVGElement, IconProps>(function Icon(
  { name, size = 16, stroke = 1.6, style, className },
  ref,
) {
  const styleRef = useElementStyle(style, ref);
  const Cmp = ICON_MAP[name];
  if (!Cmp) return null;
  return (
    <Cmp
      ref={styleRef}
      width={size}
      height={size}
      strokeWidth={stroke}
      className={cn("shrink-0", className)}
      aria-hidden="true"
    />
  );
});
