"""ML backend 协议 v2 共享 schema + 受控词表常量。"""

from aap_protocol_v2.errors import (
    LifecycleErrorCode,
    LifecycleHTTPError,
    ModelUnavailableError,
    VariantNotSupportedError,
)
from aap_protocol_v2.mask_codec import decode_low_res_mask, encode_low_res_mask
from aap_protocol_v2.mask_interaction import (
    CocoRlePayload,
    CorrectionFramePrompt,
    MAX_MASK_DIMENSION,
    MAX_MASK_PIXELS,
    MAX_MASK_RESPONSE_BYTES,
    MAX_MASK_RUNS,
    MAX_RLE_OBJECT_BYTES,
    MAX_SCRIBBLE_JSON_BYTES,
    MAX_SCRIBBLE_POINTS,
    MAX_SCRIBBLE_RASTERIZED_PIXELS,
    MAX_SCRIBBLE_STROKES,
    MaskInteractionDiagnostic,
    MaskInteractionFallback,
    MaskPromptPayload,
    NativeMaskCandidate,
    NativeMaskCandidateValue,
    ScribblePrompt,
    ScribbleStroke,
    canonical_rle_bytes,
    native_mask_candidate_id,
)
from aap_protocol_v2.predict import (
    LEGACY_CONTEXT_VARIANT_FIELDS,
    log_deprecated_model_variant_fields,
    normalize_context_model_variants,
)
from aap_protocol_v2.roles import PlatformRole
from aap_protocol_v2.schemas import (
    BatchPredictResponse,
    EvictRecord,
    LoadedKey,
    PoolStateSnapshot,
    PoolStatus,
    PredictionResult,
    TaskItem,
    WarmupResponse,
)
from aap_protocol_v2.vocab import (
    GEOMETRY_VALUES,
    INFRA_VALUES,
    INPUT_VALUES,
    PROMPT_VALUES,
    TASK_VALUES,
)
from aap_protocol_v2.version import COMPAT_PROTOCOL_VERSIONS, PROTOCOL_VERSION

__all__ = [
    "BatchPredictResponse",
    "CocoRlePayload",
    "COMPAT_PROTOCOL_VERSIONS",
    "EvictRecord",
    "CorrectionFramePrompt",
    "decode_low_res_mask",
    "encode_low_res_mask",
    "GEOMETRY_VALUES",
    "INFRA_VALUES",
    "INPUT_VALUES",
    "LEGACY_CONTEXT_VARIANT_FIELDS",
    "LoadedKey",
    "LifecycleErrorCode",
    "LifecycleHTTPError",
    "MAX_MASK_DIMENSION",
    "MAX_MASK_PIXELS",
    "MAX_MASK_RESPONSE_BYTES",
    "MAX_MASK_RUNS",
    "MAX_RLE_OBJECT_BYTES",
    "MAX_SCRIBBLE_JSON_BYTES",
    "MAX_SCRIBBLE_POINTS",
    "MAX_SCRIBBLE_RASTERIZED_PIXELS",
    "MAX_SCRIBBLE_STROKES",
    "MaskInteractionDiagnostic",
    "MaskInteractionFallback",
    "ModelUnavailableError",
    "MaskPromptPayload",
    "NativeMaskCandidate",
    "NativeMaskCandidateValue",
    "PoolStateSnapshot",
    "PoolStatus",
    "PROMPT_VALUES",
    "PROTOCOL_VERSION",
    "PredictionResult",
    "PlatformRole",
    "TASK_VALUES",
    "TaskItem",
    "ScribblePrompt",
    "ScribbleStroke",
    "VariantNotSupportedError",
    "WarmupResponse",
    "canonical_rle_bytes",
    "log_deprecated_model_variant_fields",
    "normalize_context_model_variants",
    "native_mask_candidate_id",
]
