import {
  cloneElement,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type FocusEvent as ReactFocusEvent,
} from "react";
import {
  BoldItalicUnderlineToggles,
  BlockTypeSelect,
  CodeToggle,
  CreateLink,
  InsertCodeBlock,
  InsertImage,
  InsertTable,
  ListsToggle,
  MDXEditor,
  NESTED_EDITOR_UPDATED_COMMAND,
  StrikeThroughSupSubToggles,
  UndoRedo,
  codeBlockPlugin,
  codeMirrorPlugin,
  createActiveEditorSubscription$,
  createRootEditorSubscription$,
  defaultSvgIcons,
  diffSourcePlugin,
  headingsPlugin,
  imagePlugin,
  linkDialogPlugin,
  linkPlugin,
  listsPlugin,
  markdownShortcutPlugin,
  quotePlugin,
  realmPlugin,
  rootEditor$,
  tablePlugin,
  toolbarPlugin,
  useCellValue,
  viewMode$,
  $isImageNode,
  type IconKey,
  type MDXEditorMethods,
  type Translation,
} from "@mdxeditor/editor";
import {
  $getNodeByKey,
  $getRoot,
  ElementNode,
  type LexicalEditor,
  type LexicalNode,
} from "lexical";
import { EditorView } from "@codemirror/view";
import "@mdxeditor/editor/style.css";

import { MarkdownView } from "./MarkdownView";
import { MARKDOWN_EDITOR_LABELS, translateMarkdownEditor } from "./markdownEditorLabels";
import type { MarkdownImageResolver } from "./types";
import styles from "./MarkdownEditor.module.css";

interface UploadError {
  id: string;
  file: File;
  message: string;
  anchor?: { before: string; after: string };
}

interface PendingUpload {
  id: string;
  epoch: number;
  file: File;
  source: string;
  anchor?: { before: string; after: string };
  editor?: LexicalEditor;
  nodeKey?: string;
  result?: { src: string; alt?: string };
  error?: string;
  reconciling?: boolean;
}

export interface MarkdownEditorProps {
  value: string;
  onChange: (next: string) => void;
  /** 拖拽 / 粘贴图片时上传; 返回 markdown 中要插入的 src (例如 "guide-asset:KEY"). */
  onUploadImage?: (file: File) => Promise<{ src: string; alt?: string }>;
  placeholder?: string;
  /** 编辑器离开整个交互边界时回调，工具栏和弹出框内移动不会触发。 */
  onBlur?: () => void;
  /** 用于隔离异步上传、外部同步与项目/报告切换。 */
  documentId?: string;
  /** 内部编辑区的可访问名称。 */
  label?: string;
  /** document 展示完整工具栏，compact 展示紧凑工具栏。插件能力在两种变体中保持一致。 */
  variant?: "document" | "compact";
  resolveImage?: MarkdownImageResolver;
  imageScope?: string;
  disabled?: boolean;
}

const PENDING_SOURCE_PREFIX = "markdown-upload-pending:";
const PENDING_SOURCE_LENGTH = 20;

type EditorMode = "edit" | "source" | "preview";

const editorModePlugin = realmPlugin<{ mode: EditorMode }>({
  init(realm, params) {
    if (params) realm.pub(viewMode$, params.mode === "source" ? "source" : "rich-text");
  },
  update(realm, params) {
    if (params) realm.pub(viewMode$, params.mode === "source" ? "source" : "rich-text");
  },
});

function MarkdownToolbar({ variant }: { variant: "document" | "compact" }) {
  const viewMode = useCellValue(viewMode$);
  if (viewMode === "source") {
    return <span className={styles.toolbarModeTitle}>{MARKDOWN_EDITOR_LABELS.source}</span>;
  }
  return (
    <>
      <UndoRedo />
      <BlockTypeSelect />
      <BoldItalicUnderlineToggles options={["Bold", "Italic"]} />
      <StrikeThroughSupSubToggles options={["Strikethrough"]} />
      <CodeToggle />
      <ListsToggle options={["bullet", "number", "check"]} />
      <CreateLink />
      {variant === "document" && <InsertImage />}
      {variant === "document" && <InsertTable />}
      <InsertCodeBlock />
    </>
  );
}

function isImageFile(file: File): boolean {
  return file.type.startsWith("image/");
}

function isEditorBoundaryTarget(target: EventTarget | null, root: HTMLElement | null): boolean {
  if (!(target instanceof Node)) return false;
  if (root?.contains(target)) return true;
  const popup = target instanceof Element ? target.closest(".mdxeditor-popup-container") : null;
  return Boolean(popup && root?.contains(popup));
}

function imagePlaceholderSource(id: string): string {
  return `${PENDING_SOURCE_PREFIX}${id}`;
}

export function imagePlaceholderMarkdown(source: string): string {
  // The visual placeholder communicates progress. Keep Markdown alt empty so
  // reconciliation can fill the filename without overwriting an author edit.
  return `![](${source})`;
}

export function resolveUploadedImageAlt(
  currentAlt: string,
  filename: string,
  resultAlt?: string,
): string {
  return currentAlt.trim() ? currentAlt : (resultAlt ?? filename);
}

/**
 * Remove only image syntax generated by this editor's upload queue.
 *
 * MDXEditor exports ImageNode values as inline images. The source is a
 * cryptographically-uninteresting but unique per-upload marker, so matching
 * that exact source cannot alter ordinary author Markdown. The actual image
 * node is reconciled through Lexical below; this function only keeps the
 * controlled parent draft free of a temporary URL between transactions.
 */
type PendingSource = PendingUpload | string;

function pendingSourceValue(item: PendingSource): string {
  return typeof item === "string" ? item : item.source;
}

function pendingImagePattern(source: string): RegExp {
  const escapedSource = source.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(
    `!\\[((?:\\\\.|[^\\]\\n])*)\\]\\(\\s*<?${escapedSource}>?(?:\\s+(?:"(?:\\\\.|[^"])*"|'(?:\\\\.|[^'])*'|\\((?:\\\\.|[^)])*\\)))?\\s*\\)`,
    "g",
  );
}

export function stripPendingImageNodes(markdown: string, pending: Iterable<PendingSource>): string {
  let next = markdown;
  for (const item of pending) {
    next = next.replace(pendingImagePattern(pendingSourceValue(item)), "");
  }
  return next;
}

function pendingImageBounds(
  markdown: string,
  source: string,
): { start: number; end: number } | null {
  const sourceIndex = markdown.indexOf(source);
  if (sourceIndex < 0) return null;
  const pattern = pendingImagePattern(source);
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(markdown)) !== null) {
    const start = match.index;
    const end = start + match[0].length;
    if (sourceIndex >= start && sourceIndex < end) return { start, end };
  }
  return null;
}

function pendingImageAnchor(
  markdown: string,
  source: string,
): { before: string; after: string } | undefined {
  const bounds = pendingImageBounds(markdown, source);
  if (!bounds) return undefined;
  return {
    before: markdown.slice(Math.max(0, bounds.start - PENDING_SOURCE_LENGTH), bounds.start),
    after: markdown.slice(bounds.end, bounds.end + PENDING_SOURCE_LENGTH),
  };
}

const TABLE_CELL_DRAFT_SYNC_DELAY_MS = 250;

/**
 * Table cells are independent Lexical editors. MDXEditor's public active
 * editor subscription and nested editor command are the smallest supported
 * way to export a changed cell into the root editor; this avoids serializing
 * the whole document on every key.
 */
function isTableCellEditor(editor: LexicalEditor): boolean {
  const parentTagName = editor.getRootElement()?.parentElement?.tagName;
  return parentTagName === "TD" || parentTagName === "TH";
}

function registerTableCellDraftSync(editor: LexicalEditor): () => void {
  let timer: number | null = null;

  const cancel = () => {
    if (timer !== null) {
      window.clearTimeout(timer);
      timer = null;
    }
  };

  const schedule = () => {
    cancel();
    timer = window.setTimeout(() => {
      timer = null;
      if (editor.isComposing()) {
        schedule();
        return;
      }

      const root = editor.getRootElement();
      const hadFocus = Boolean(root && root.contains(document.activeElement));
      editor.dispatchCommand(NESTED_EDITOR_UPDATED_COMMAND, undefined);
      // saveAndFocus(null) updates the table's active-cell marker. Reapply
      // focus only when this cell still owned focus, preserving selection
      // and preventing an idle timer from stealing focus after navigation.
      if (hadFocus) editor.focus();
    }, TABLE_CELL_DRAFT_SYNC_DELAY_MS);
  };

  const unregisterUpdate = editor.registerUpdateListener(({ dirtyElements, dirtyLeaves }) => {
    // Selection-only updates have no dirty nodes and must not publish a
    // duplicate Markdown draft.
    if (dirtyElements.size === 0 && dirtyLeaves.size === 0) return;
    schedule();
  });

  return () => {
    cancel();
    unregisterUpdate();
  };
}

function visitLexicalNodes(node: LexicalNode, visit: (node: LexicalNode) => void): void {
  visit(node);
  if (node instanceof ElementNode) {
    node.getChildren().forEach((child) => visitLexicalNodes(child, visit));
  }
}

interface PendingImagePluginParams {
  getPending: () => Map<string, PendingUpload>;
  onImageNode: (editor: LexicalEditor, nodeKey: string, pending: PendingUpload) => void;
  onMissingNode: (editor: LexicalEditor, pending: PendingUpload) => void;
}

/**
 * Reconcile uploads by ImageNode identity. A Markdown scan cannot distinguish
 * a reference image, an image moved by the author, and a text occurrence of a
 * URL. Lexical gives us the exact node and transaction that owns the marker.
 */
const pendingImagePlugin = realmPlugin<PendingImagePluginParams>({
  init(realm, params) {
    if (!params) return;
    realm.pub(createRootEditorSubscription$, (editor) =>
      editor.registerUpdateListener(({ editorState }) => {
        const seen = new Set<string>();
        editorState.read(() => {
          visitLexicalNodes($getRoot(), (node) => {
            if (!$isImageNode(node)) return;
            const source = node.getSrc();
            if (!source.startsWith(PENDING_SOURCE_PREFIX)) return;
            const pendingId = source.slice(PENDING_SOURCE_PREFIX.length);
            const pending = params.getPending().get(pendingId);
            if (!pending) return;
            seen.add(pendingId);
            params.onImageNode(editor, node.getKey(), pending);
          });
        });

        for (const pending of params.getPending().values()) {
          if (pending.nodeKey && !seen.has(pending.id)) {
            params.onMissingNode(editor, pending);
          }
        }
      }),
    );
  },
});

function PendingImagePlaceholder() {
  return (
    <span className={styles.imagePlaceholder} role="status">
      图片上传中…
    </span>
  );
}

/**
 * Lazy-loaded by the guide, template and BUG forms. MDXEditor emits an
 * initial
 * normalization callback when importing a document; that callback is
 * intentionally ignored so opening a document never creates a write.
 */
function MarkdownEditorDocument({
  value,
  onChange,
  onUploadImage,
  placeholder,
  onBlur,
  documentId,
  label = "Markdown 编辑器",
  variant = "document",
  resolveImage,
  imageScope,
  disabled = false,
}: MarkdownEditorProps) {
  const rootRef = useRef<HTMLDivElement | null>(null);
  const editorRef = useRef<MDXEditorMethods | null>(null);
  const onChangeRef = useRef(onChange);
  const onBlurRef = useRef(onBlur);
  const onUploadRef = useRef(onUploadImage);
  const resolveImageRef = useRef(resolveImage);
  const valueRef = useRef(value);
  const latestMarkdownRef = useRef(value);
  const editorMarkdownRef = useRef(value);
  const initialSourceRef = useRef(value);
  const initialNormalizedRef = useRef<string | null>(null);
  const currentDocumentRef = useRef(documentId);
  const epochRef = useRef(0);
  const uploadQueueRef = useRef<Promise<void>>(Promise.resolve());
  const pendingUploadsRef = useRef<Map<string, PendingUpload>>(new Map());
  const blurTimerRef = useRef<number | null>(null);
  const compositionFlushTimerRef = useRef<number | null>(null);
  const composingRef = useRef(false);
  const deferredPublishRef = useRef<string | null>(null);
  const aliveRef = useRef(true);
  const reconcilePendingRef = useRef<
    (editor: LexicalEditor, nodeKey: string, pending: PendingUpload) => void
  >(() => undefined);
  const missingPendingRef = useRef<(editor: LexicalEditor, pending: PendingUpload) => void>(
    () => undefined,
  );
  const [uploadErrors, setUploadErrors] = useState<UploadError[]>([]);
  const [parseError, setParseError] = useState<string | null>(null);
  const [mode, setMode] = useState<EditorMode>("edit");
  const [overlayContainer, setOverlayContainer] = useState<HTMLElement | null>(null);

  onChangeRef.current = onChange;
  onBlurRef.current = onBlur;
  onUploadRef.current = onUploadImage;
  resolveImageRef.current = resolveImage;
  valueRef.current = value;

  useEffect(() => {
    // React StrictMode intentionally mounts effects twice in development. The
    // ref must become live again for the second mount or uploads are ignored.
    aliveRef.current = true;
    return () => {
      aliveRef.current = false;
      if (blurTimerRef.current !== null) window.clearTimeout(blurTimerRef.current);
      if (compositionFlushTimerRef.current !== null) {
        window.clearTimeout(compositionFlushTimerRef.current);
      }
    };
  }, []);

  // MDXEditor's DownshiftAutoComplete omits the id that its surrounding label
  // references. Add an explicit accessible name when the link dialog portal
  // appears so keyboard and screen-reader users can identify the URL field.
  useEffect(() => {
    const root = rootRef.current;
    if (!root) return;

    const applyLinkUrlLabel = () => {
      root
        .querySelectorAll<HTMLInputElement>('.mdxeditor-popup-container input[name="url"]')
        .forEach((input) => input.setAttribute("aria-label", "地址"));
    };

    applyLinkUrlLabel();
    if (typeof MutationObserver === "undefined") return;
    const observer = new MutationObserver(applyLinkUrlLabel);
    observer.observe(root, { childList: true, subtree: true });
    return () => observer.disconnect();
  }, []);

  const currentEditorMarkdown = useCallback(() => {
    const markdown = editorRef.current?.getMarkdown();
    if (typeof markdown === "string") {
      editorMarkdownRef.current = markdown;
      return markdown;
    }
    return editorMarkdownRef.current;
  }, []);

  const validDraftFromEditor = useCallback(() => {
    return stripPendingImageNodes(currentEditorMarkdown(), pendingUploadsRef.current.values());
  }, [currentEditorMarkdown]);

  const publishValidDraft = useCallback((next: string) => {
    latestMarkdownRef.current = next;
    if (composingRef.current) {
      deferredPublishRef.current = next;
      return;
    }
    deferredPublishRef.current = null;
    if (next !== valueRef.current) onChangeRef.current(next);
  }, []);

  const flushDeferredCompositionDraft = useCallback(() => {
    if (compositionFlushTimerRef.current !== null) {
      window.clearTimeout(compositionFlushTimerRef.current);
    }
    compositionFlushTimerRef.current = window.setTimeout(() => {
      compositionFlushTimerRef.current = null;
      if (composingRef.current) return;
      const deferred = deferredPublishRef.current;
      deferredPublishRef.current = null;
      if (deferred !== null) publishValidDraft(deferred);
    }, 0);
  }, [publishValidDraft]);

  const handleCompositionStart = useCallback(() => {
    composingRef.current = true;
  }, []);

  const handleCompositionEnd = useCallback(() => {
    composingRef.current = false;
    flushDeferredCompositionDraft();
  }, [flushDeferredCompositionDraft]);

  const settleAfterPendingTransaction = useCallback(() => {
    queueMicrotask(() => {
      if (!aliveRef.current) return;
      publishValidDraft(validDraftFromEditor());
    });
  }, [publishValidDraft, validDraftFromEditor]);

  const reconcilePendingImage = useCallback(
    (editor: LexicalEditor, nodeKey: string, pending: PendingUpload) => {
      if (!aliveRef.current || pending.epoch !== epochRef.current || pending.reconciling) {
        return;
      }
      pending.editor = editor;
      pending.nodeKey = nodeKey;
      const result = pending.result;
      const errorMessage = pending.error;
      if (!result && !errorMessage) return;

      pending.reconciling = true;
      // Remove the record before the Lexical transaction. The transaction's
      // regular MDXEditor onChange callback can then publish the real source
      // instead of treating it as another pending marker.
      pendingUploadsRef.current.delete(pending.id);

      editor.update(
        () => {
          const node = $getNodeByKey(nodeKey);
          if (!$isImageNode(node) || node.getSrc() !== pending.source) return;
          if (result) {
            node.setSrc(result.src);
            // An author may edit alt text while the upload is in flight. Only
            // fill the empty value created by MDXEditor's upload command.
            node.setAltText(
              resolveUploadedImageAlt(node.getAltText(), pending.file.name, result.alt),
            );
          } else {
            node.remove();
          }
        },
        {
          onUpdate: () => {
            pending.reconciling = false;
            if (errorMessage) {
              if (aliveRef.current && pending.epoch === epochRef.current) {
                setUploadErrors((errors) => [
                  ...errors.filter((error) => error.id !== pending.id),
                  {
                    id: pending.id,
                    file: pending.file,
                    message: errorMessage,
                    anchor: pending.anchor,
                  },
                ]);
              }
            } else {
              setUploadErrors((errors) => errors.filter((error) => error.id !== pending.id));
            }
            settleAfterPendingTransaction();
          },
        },
      );
    },
    [settleAfterPendingTransaction],
  );

  reconcilePendingRef.current = reconcilePendingImage;

  const handleMissingPendingImage = useCallback(
    (editor: LexicalEditor, pending: PendingUpload) => {
      if (!aliveRef.current || pending.epoch !== epochRef.current || pending.reconciling) return;
      pendingUploadsRef.current.delete(pending.id);
      if (pending.error) {
        const message = pending.error;
        setUploadErrors((errors) => [
          ...errors.filter((error) => error.id !== pending.id),
          {
            id: pending.id,
            file: pending.file,
            message,
            anchor: pending.anchor,
          },
        ]);
      }
      // Keep the editor argument in the callback so the plugin remains tied
      // to the active Lexical instance; reading it also makes this path safe
      // when a document is replaced during an upload.
      void editor;
      settleAfterPendingTransaction();
    },
    [settleAfterPendingTransaction],
  );

  missingPendingRef.current = handleMissingPendingImage;

  const pendingPlugin = useMemo(
    () =>
      pendingImagePlugin({
        getPending: () => pendingUploadsRef.current,
        onImageNode: (editor, nodeKey, pending) =>
          reconcilePendingRef.current(editor, nodeKey, pending),
        onMissingNode: (editor, pending) => missingPendingRef.current(editor, pending),
      }),
    [],
  );

  const tableCellDraftPlugin = useMemo(
    () =>
      realmPlugin({
        init(realm) {
          realm.pub(createActiveEditorSubscription$, (editor) => {
            if (editor === realm.getValue(rootEditor$) || !isTableCellEditor(editor)) {
              return () => undefined;
            }
            return registerTableCellDraftSync(editor);
          });
        },
      })(),
    [],
  );

  const syncMarkdown = useCallback((next: string) => {
    editorMarkdownRef.current = next;
    editorRef.current?.setMarkdown(next);
  }, []);

  const completeUpload = useCallback(
    (pending: PendingUpload, result: { src: string; alt?: string }) => {
      if (!aliveRef.current || pending.epoch !== epochRef.current) return;
      pending.result = result;
      pending.error = undefined;
      // The plugin observes the ImageNode by identity after MDXEditor imports
      // the returned marker. If the upload finished first, it reconciles when
      // the node is inserted; if the node was already observed, schedule a
      // harmless export update so the active transaction sees the result.
      if (pending.nodeKey) {
        const editor = pending.editor;
        if (editor) reconcilePendingRef.current(editor, pending.nodeKey, pending);
      }
    },
    [],
  );

  const failUpload = useCallback((pending: PendingUpload, error: unknown) => {
    if (!aliveRef.current || pending.epoch !== epochRef.current) return;
    pending.error = error instanceof Error ? error.message : "网络或权限错误";
    pending.result = undefined;
    // A node already observed by the plugin can be reconciled immediately;
    // otherwise its next Lexical update will do so after insertion.
    if (pending.nodeKey) {
      const editor = pending.editor;
      if (editor) reconcilePendingRef.current(editor, pending.nodeKey, pending);
    }
  }, []);

  const runUpload = useCallback(
    (pending: PendingUpload) => {
      const task = uploadQueueRef.current.then(async () => {
        if (!aliveRef.current || pending.epoch !== epochRef.current) return;
        const upload = onUploadRef.current;
        if (!upload) {
          failUpload(pending, new Error("当前编辑器不支持图片上传"));
          return;
        }
        try {
          const result = await upload(pending.file);
          completeUpload(pending, result);
        } catch (error: unknown) {
          failUpload(pending, error);
        }
      });
      uploadQueueRef.current = task.then(
        () => undefined,
        () => undefined,
      );
    },
    [completeUpload, failUpload],
  );

  const beginUpload = useCallback(
    (file: File): string => {
      const id = `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
      const pending: PendingUpload = {
        id,
        epoch: epochRef.current,
        file,
        source: imagePlaceholderSource(id),
      };
      pendingUploadsRef.current.set(id, pending);
      runUpload(pending);
      return pending.source;
    },
    [runUpload],
  );

  const uploadHandler = useCallback(
    async (file: File): Promise<string> => {
      if (!isImageFile(file) || !onUploadRef.current) {
        throw new Error("当前编辑器不支持图片上传");
      }
      // Return a source only. MDXEditor inserts the ImageNode at the current
      // selection; the Lexical plugin above replaces that exact node after
      // the serialized upload queue resolves.
      return beginUpload(file);
    },
    [beginUpload],
  );

  const insertPlaceholderAtAnchor = useCallback(
    (pending: PendingUpload) => {
      const current = currentEditorMarkdown();
      if (current.includes(pending.source)) return;

      const anchor = pending.anchor;
      let insertAt = -1;
      if (anchor?.before) {
        const beforeAt = current.lastIndexOf(anchor.before);
        if (beforeAt >= 0) insertAt = beforeAt + anchor.before.length;
      }
      if (insertAt < 0 && anchor?.after) insertAt = current.indexOf(anchor.after);
      const insertion = imagePlaceholderMarkdown(pending.source);
      const next =
        insertAt >= 0
          ? `${current.slice(0, insertAt)}${insertion}${current.slice(insertAt)}`
          : `${current}${current.endsWith("\n") || current.length === 0 ? "" : "\n"}${insertion}`;
      syncMarkdown(next);
    },
    [currentEditorMarkdown, syncMarkdown],
  );

  const retryUpload = useCallback(
    (id: string) => {
      const error = uploadErrors.find((item) => item.id === id);
      if (!error || !onUploadRef.current) return;
      const pending: PendingUpload = {
        id: error.id,
        epoch: epochRef.current,
        file: error.file,
        source: imagePlaceholderSource(error.id),
        anchor: error.anchor,
      };
      pendingUploadsRef.current.set(id, pending);
      insertPlaceholderAtAnchor(pending);
      setUploadErrors((errors) => errors.filter((item) => item.id !== id));
      runUpload(pending);
    },
    [insertPlaceholderAtAnchor, runUpload, uploadErrors],
  );

  const handleEditorChange = useCallback(
    (next: string, initialMarkdownNormalize: boolean) => {
      editorMarkdownRef.current = next;
      if (initialMarkdownNormalize) {
        initialNormalizedRef.current = next;
        return;
      }

      setParseError(null);
      const pending = pendingUploadsRef.current;
      for (const item of pending.values()) {
        if (item.anchor || !next.includes(item.source)) continue;
        item.anchor = pendingImageAnchor(next, item.source);
      }

      // Undoing the first edit should restore the exact source supplied by
      // the caller, even if MDXEditor's importer normalized equivalent syntax.
      const restoredInitial =
        pending.size === 0 &&
        initialNormalizedRef.current !== null &&
        next === initialNormalizedRef.current
          ? initialSourceRef.current
          : stripPendingImageNodes(next, pending.values());
      publishValidDraft(restoredInitial);
    },
    [publishValidDraft],
  );

  const handleEditorBlur = useCallback((event: FocusEvent) => {
    if (blurTimerRef.current !== null) window.clearTimeout(blurTimerRef.current);
    blurTimerRef.current = window.setTimeout(() => {
      blurTimerRef.current = null;
      const active = document.activeElement;
      if (isEditorBoundaryTarget(active, rootRef.current)) return;
      if (!isEditorBoundaryTarget(event.relatedTarget, rootRef.current)) onBlurRef.current?.();
    }, 0);
  }, []);

  const handleParseError = useCallback((payload: { error: string; source: string }) => {
    editorMarkdownRef.current = payload.source;
    latestMarkdownRef.current = stripPendingImageNodes(
      payload.source,
      pendingUploadsRef.current.values(),
    );
    setParseError(payload.error);
  }, []);

  const imagePreviewHandler = useCallback(async (src: string): Promise<string> => {
    if (src.startsWith(PENDING_SOURCE_PREFIX)) {
      // Keep the editor's own placeholder visible until the ImageNode is
      // replaced. Resolving to a broken URL would make loading look like a
      // missing asset.
      return new Promise<string>(() => undefined);
    }
    if (!src.startsWith("guide-asset:")) return src;
    const resolver = resolveImageRef.current;
    const epoch = epochRef.current;
    if (!resolver) return src;
    try {
      const resolved = await resolver(src);
      if (!aliveRef.current || epoch !== epochRef.current) return src;
      return resolved?.url ?? src;
    } catch {
      return src;
    }
  }, []);

  useEffect(() => {
    const documentChanged = currentDocumentRef.current !== documentId;
    const editor = editorRef.current;
    if (documentChanged) {
      currentDocumentRef.current = documentId;
      epochRef.current += 1;
      pendingUploadsRef.current.clear();
      uploadQueueRef.current = Promise.resolve();
      setUploadErrors([]);
      setParseError(null);
      initialSourceRef.current = value;
      initialNormalizedRef.current = null;
      latestMarkdownRef.current = value;
      editorMarkdownRef.current = value;
      editor?.setMarkdown(value);
      setMode("edit");
      return;
    }

    if (editor && latestMarkdownRef.current !== value) {
      // A controlled value that differs while a marker is pending is an
      // external replacement. Drop the old async ownership before importing
      // the new document so a late completion cannot reappear in it.
      if (pendingUploadsRef.current.size > 0) {
        epochRef.current += 1;
        pendingUploadsRef.current.clear();
        uploadQueueRef.current = Promise.resolve();
        setUploadErrors([]);
      }
      initialSourceRef.current = value;
      initialNormalizedRef.current = null;
      latestMarkdownRef.current = value;
      editorMarkdownRef.current = value;
      editor.setMarkdown(value);
      setParseError(null);
    }
  }, [documentId, value]);

  const translation: Translation = useCallback(
    (key, defaultValue, interpolations) => {
      if (key === "contentArea.editableMarkdown") return label;
      return translateMarkdownEditor(key, defaultValue, interpolations);
    },
    [label],
  );

  const iconComponentFor = useCallback((name: IconKey) => {
    const icon = defaultSvgIcons[name];
    if (name === "add_row" || name === "add_column") {
      const accessibleLabel = name === "add_row" ? "向下插入行" : "向右插入列";
      return cloneElement(icon, {
        role: "img",
        "aria-label": accessibleLabel,
        title: accessibleLabel,
      });
    }
    return icon;
  }, []);

  const plugins = useMemo(() => {
    return [
      headingsPlugin(),
      listsPlugin(),
      quotePlugin(),
      linkPlugin(),
      linkDialogPlugin(),
      tablePlugin(),
      codeBlockPlugin({ defaultCodeBlockLanguage: "text" }),
      codeMirrorPlugin({
        codeBlockLanguages: {
          text: "纯文本",
          bash: "Bash",
          css: "CSS",
          html: "HTML",
          javascript: "JavaScript",
          json: "JSON",
          python: "Python",
          typescript: "TypeScript",
          tsx: "TypeScript React",
        },
        codeMirrorExtensions: [EditorView.contentAttributes.of({ "aria-label": label })],
      }),
      imagePlugin({
        imageUploadHandler: onUploadImage ? uploadHandler : null,
        imagePreviewHandler: onUploadImage || resolveImage ? imagePreviewHandler : null,
        imagePlaceholder: onUploadImage ? PendingImagePlaceholder : null,
        disableImageResize: true,
        allowSetImageDimensions: false,
      }),
      diffSourcePlugin({ viewMode: "rich-text" }),
      markdownShortcutPlugin(),
      pendingPlugin,
      tableCellDraftPlugin,
      editorModePlugin({ mode }),
      toolbarPlugin({ toolbarContents: () => <MarkdownToolbar variant={variant} /> }),
    ];
  }, [
    imagePreviewHandler,
    label,
    onUploadImage,
    pendingPlugin,
    resolveImage,
    mode,
    tableCellDraftPlugin,
    uploadHandler,
    variant,
  ]);

  return (
    <div
      ref={rootRef}
      className={`${styles.root} ${variant === "compact" ? styles.compact : styles.document}`}
      data-testid="markdown-editor"
      data-image-scope={imageScope}
      onCompositionStartCapture={handleCompositionStart}
      onCompositionEndCapture={handleCompositionEnd}
      onBlurCapture={(event: ReactFocusEvent<HTMLDivElement>) =>
        handleEditorBlur(event.nativeEvent)
      }
    >
      <div className={styles.modeBar} role="tablist" aria-label="Markdown 编辑模式">
        <button
          type="button"
          role="tab"
          aria-selected={mode === "edit"}
          className={mode === "edit" ? styles.modeButtonActive : styles.modeButton}
          onClick={() => setMode("edit")}
        >
          {MARKDOWN_EDITOR_LABELS.edit}
        </button>
        <button
          type="button"
          role="tab"
          aria-selected={mode === "source"}
          className={mode === "source" ? styles.modeButtonActive : styles.modeButton}
          onClick={() => setMode("source")}
        >
          {MARKDOWN_EDITOR_LABELS.source}
        </button>
        <button
          type="button"
          role="tab"
          aria-selected={mode === "preview"}
          className={mode === "preview" ? styles.modeButtonActive : styles.modeButton}
          onClick={() => setMode("preview")}
        >
          {MARKDOWN_EDITOR_LABELS.preview}
        </button>
      </div>

      <div className={mode === "preview" ? styles.editorSurfaceHidden : undefined}>
        <div ref={setOverlayContainer} className={styles.overlayHost}>
          {overlayContainer && (
            <MDXEditor
              ref={editorRef}
              markdown={value}
              onChange={handleEditorChange}
              onBlur={handleEditorBlur}
              onError={handleParseError}
              plugins={plugins}
              className={styles.mdxEditor}
              contentEditableClassName={styles.contentEditable}
              placeholder={placeholder}
              readOnly={disabled}
              spellCheck
              suppressHtmlProcessing
              translation={translation}
              iconComponentFor={iconComponentFor}
              overlayContainer={overlayContainer}
              trim={false}
            />
          )}
        </div>
      </div>

      {mode === "preview" && (
        <div className={styles.previewSurface} data-testid="markdown-preview">
          <MarkdownView content={value} resolveImage={resolveImage} imageScope={imageScope} />
        </div>
      )}

      {parseError && (
        <div className={styles.parseError} role="alert" data-testid="markdown-parse-error">
          <strong>无法以可视化模式解析当前内容。</strong>
          <span>原文已保留，请切换“源码”检查或修复 Markdown。</span>
          <code>{parseError}</code>
        </div>
      )}

      {uploadErrors.length > 0 && (
        <div
          className={styles.uploadErrors}
          aria-live="polite"
          data-testid="markdown-upload-errors"
        >
          {uploadErrors.map((error) => (
            <div className={styles.uploadError} role="alert" key={error.id}>
              <span>
                图片“{error.file.name}”上传失败：{error.message}
              </span>
              <button type="button" onClick={() => retryUpload(error.id)} disabled={disabled}>
                重试
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

/**
 * Keep asynchronous upload and Lexical state owned by one document instance.
 * A keyed inner owner unmounts the old editor during a document switch before
 * a late upload callback can observe the new props.
 */
export function MarkdownEditor(props: MarkdownEditorProps) {
  return <MarkdownEditorDocument key={props.documentId ?? "default-document"} {...props} />;
}

export default MarkdownEditor;
