"""Authoritative task discussion read model.

The legacy ``annotation_comments`` table and the native task-comment rows in
``annotation_feedbacks`` are both still write-owned by their existing APIs.  This
module only composes their identifiers for one keyset-ordered read, then hydrates
each source in batches.  Annotation feedback mirrors, Issue threads, BUGs and task
rejection mirrors are intentionally not part of this read model.
"""

from __future__ import annotations

import base64
import binascii
import json
import uuid
from dataclasses import dataclass
from datetime import datetime
from typing import Literal

from fastapi import HTTPException
from sqlalchemy import and_, func, literal, or_, select, union_all
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.v1.tasks._shared import _assert_task_visible
from app.db.enums import UserRole
from app.db.models.annotation import Annotation
from app.db.models.annotation_comment import AnnotationComment
from app.db.models.annotation_feedback import AnnotationFeedback
from app.db.models.task import Task
from app.db.models.user import User
from app.schemas.annotation_comment import (
    AnnotationCommentOut,
    TaskDiscussionItem,
    TaskDiscussionPage,
)
from app.schemas.annotation_feedback import AnnotationFeedbackOut
from app.services.discussion_actions import discussion_actions
from app.services.user_brief import resolve_briefs


DiscussionScope = Literal["all", "task", "annotation"]
DiscussionSource = Literal["annotation_comment", "feedback"]

_CURSOR_VERSION = 1
_MAX_CURSOR_LENGTH = 2048
_DISCUSSION_SOURCES = frozenset(("annotation_comment", "feedback"))


@dataclass(frozen=True)
class DiscussionCursor:
    """Decoded position plus the query binding carried by a cursor."""

    task_id: uuid.UUID
    scope: DiscussionScope
    annotation_id: uuid.UUID | None
    created_at: datetime
    source: DiscussionSource
    item_id: uuid.UUID


def encode_discussion_cursor(
    *,
    task_id: uuid.UUID,
    scope: DiscussionScope,
    annotation_id: uuid.UUID | None,
    created_at: datetime,
    source: DiscussionSource,
    item_id: uuid.UUID,
) -> str:
    """Encode a versioned, query-bound keyset cursor.

    JSON rather than a delimiter-only payload keeps the binding unambiguous as the
    contract evolves.  The result is URL-safe base64 and deliberately opaque to
    callers.
    """

    payload = {
        "version": _CURSOR_VERSION,
        "task_id": str(task_id),
        "scope": scope,
        "annotation_id": str(annotation_id) if annotation_id is not None else None,
        "created_at": created_at.isoformat(),
        "source": source,
        "id": str(item_id),
    }
    encoded = base64.urlsafe_b64encode(
        json.dumps(payload, separators=(",", ":"), sort_keys=True).encode("utf-8")
    ).decode("ascii")
    # This is a defensive assertion for future additions to the payload.  A cursor
    # generated by the service must always be consumable by the public endpoint.
    if len(encoded) > _MAX_CURSOR_LENGTH:  # pragma: no cover - future-proof guard
        raise ValueError("discussion cursor exceeds maximum length")
    return encoded


def _invalid_cursor() -> HTTPException:
    return HTTPException(status_code=400, detail="invalid_cursor")


def decode_discussion_cursor(
    raw: str,
    *,
    task_id: uuid.UUID,
    scope: DiscussionScope,
    annotation_id: uuid.UUID | None,
) -> DiscussionCursor:
    """Decode and validate a cursor against the request's query scope.

    Cursors are bound to task, scope and annotation so a cursor copied from another
    list cannot silently skip records.  All malformed and mismatched values use the
    same 400 response as the existing keyset APIs.
    """

    if len(raw) > _MAX_CURSOR_LENGTH:
        raise _invalid_cursor()
    try:
        decoded = base64.b64decode(raw.encode("ascii"), altchars=b"-_", validate=True)
        payload = json.loads(decoded.decode("utf-8"))
        if not isinstance(payload, dict):
            raise ValueError

        if payload.get("version") != _CURSOR_VERSION:
            raise ValueError
        cursor_task_id = uuid.UUID(str(payload["task_id"]))
        if cursor_task_id != task_id:
            raise ValueError
        cursor_scope = payload["scope"]
        if cursor_scope not in {"all", "task", "annotation"}:
            raise ValueError
        if cursor_scope != scope:
            raise ValueError

        raw_annotation_id = payload.get("annotation_id")
        cursor_annotation_id = (
            uuid.UUID(str(raw_annotation_id)) if raw_annotation_id is not None else None
        )
        if cursor_annotation_id != annotation_id:
            raise ValueError
        if scope == "annotation" and cursor_annotation_id is None:
            raise ValueError
        if scope != "annotation" and cursor_annotation_id is not None:
            raise ValueError

        created_at = datetime.fromisoformat(str(payload["created_at"]))
        # Database timestamps are timezone-aware.  Rejecting a naive client cursor
        # avoids an otherwise surprising aware/naive comparison at query time.
        if created_at.tzinfo is None or created_at.utcoffset() is None:
            raise ValueError
        source = payload["source"]
        if source not in _DISCUSSION_SOURCES:
            raise ValueError
        item_id = uuid.UUID(str(payload["id"]))
    except (
        KeyError,
        TypeError,
        ValueError,
        UnicodeError,
        binascii.Error,
        json.JSONDecodeError,
    ) as exc:
        raise _invalid_cursor() from exc

    return DiscussionCursor(
        task_id=cursor_task_id,
        scope=cursor_scope,
        annotation_id=cursor_annotation_id,
        created_at=created_at,
        source=source,
        item_id=item_id,
    )


async def require_visible_task(
    db: AsyncSession,
    task_id: uuid.UUID,
    user: User,
) -> Task:
    """Resolve a task and apply the repository's batch/project visibility rules."""

    task = await db.get(Task, task_id)
    if task is None:
        raise HTTPException(status_code=404, detail="Task not found")
    await _assert_task_visible(db, task, user)
    return task


async def require_visible_annotation(
    db: AsyncSession,
    annotation_id: uuid.UUID,
    user: User,
    *,
    task_id: uuid.UUID | None = None,
    require_active: bool = False,
) -> tuple[Annotation, Task]:
    """Resolve annotation → actual task and enforce task visibility.

    The annotation's project column is not used as an authority.  Historical active
    comments remain readable after an annotation is soft-deleted, while write/upload
    callers can opt into the existing active-annotation requirement.
    """

    annotation = await db.get(Annotation, annotation_id)
    if annotation is None:
        raise HTTPException(status_code=404, detail="Annotation not found")
    if task_id is not None and annotation.task_id != task_id:
        raise HTTPException(status_code=404, detail="Annotation not found")
    if require_active and (not annotation.is_active or bool(annotation.was_cancelled)):
        raise HTTPException(status_code=404, detail="Annotation not found")

    task = await require_visible_task(db, annotation.task_id, user)
    return annotation, task


def _annotation_comment_out(
    comment: AnnotationComment, author_name: str | None
) -> AnnotationCommentOut:
    return AnnotationCommentOut(
        id=comment.id,
        annotation_id=comment.annotation_id,
        project_id=comment.project_id,
        author_id=comment.author_id,
        author_name=author_name,
        body=comment.body,
        is_resolved=comment.is_resolved,
        is_active=comment.is_active,
        mentions=comment.mentions or [],
        attachments=comment.attachments or [],
        canvas_drawing=comment.canvas_drawing,
        anchor=comment.anchor,
        created_at=comment.created_at,
        updated_at=comment.updated_at,
    )


def _feedback_out(
    feedback: AnnotationFeedback, author_name: str | None
) -> AnnotationFeedbackOut:
    return AnnotationFeedbackOut(
        id=feedback.id,
        kind=feedback.kind,
        anchor_type=feedback.anchor_type,
        project_id=feedback.project_id,
        task_id=feedback.task_id,
        annotation_id=feedback.annotation_id,
        anchor_position=feedback.anchor_position,
        status=feedback.status,
        severity=feedback.severity,
        title=feedback.title,
        body=feedback.body,
        author_id=feedback.author_id,
        author_name=author_name,
        attachments=feedback.attachments or [],
        thread_parent_id=feedback.thread_parent_id,
        is_active=feedback.is_active,
        resolved_at=feedback.resolved_at,
        resolved_by_id=feedback.resolved_by_id,
        created_at=feedback.created_at,
        updated_at=feedback.updated_at,
    )


def _actions_for(*, source: DiscussionSource, author_id: uuid.UUID, user: User):
    is_admin = user.role in {UserRole.SUPER_ADMIN, UserRole.PROJECT_ADMIN}
    return discussion_actions(
        source,
        "comment",
        is_author=author_id == user.id,
        is_admin=is_admin,
        is_reviewer=user.role == UserRole.REVIEWER,
        is_accessible=True,
        # Native task comments and legacy annotation comments have no Issue thread
        # affordance in this product scope.
        can_reply=False,
    )


def _identifier_selects(
    *,
    task_id: uuid.UUID,
    scope: DiscussionScope,
    annotation_id: uuid.UUID | None,
    project_id: uuid.UUID,
):
    """Return the source identifier SELECTs used by the single read model query."""

    selects = []
    if scope in {"all", "annotation"}:
        annotation_query = (
            select(
                AnnotationComment.id.label("item_id"),
                AnnotationComment.created_at.label("created_at"),
                literal("annotation_comment").label("source"),
            )
            .join(Annotation, Annotation.id == AnnotationComment.annotation_id)
            .where(
                Annotation.task_id == task_id,
                AnnotationComment.is_active.is_(True),
            )
        )
        if annotation_id is not None:
            annotation_query = annotation_query.where(Annotation.id == annotation_id)
        selects.append(annotation_query)

    if scope in {"all", "task"}:
        # ``anchor_type=task`` and a NULL parent identify native task-comment roots.
        # Joining the task project in the predicate guards malformed legacy rows whose
        # denormalized project_id no longer agrees with the actual task.
        selects.append(
            select(
                AnnotationFeedback.id.label("item_id"),
                AnnotationFeedback.created_at.label("created_at"),
                literal("feedback").label("source"),
            ).where(
                AnnotationFeedback.project_id == project_id,
                AnnotationFeedback.task_id == task_id,
                AnnotationFeedback.kind == "comment",
                AnnotationFeedback.anchor_type == "task",
                AnnotationFeedback.thread_parent_id.is_(None),
                AnnotationFeedback.is_active.is_(True),
            )
        )
    return selects


async def list_task_discussion(
    db: AsyncSession,
    *,
    task: Task,
    user: User,
    scope: DiscussionScope,
    annotation_id: uuid.UUID | None,
    limit: int,
    cursor: str | None = None,
) -> TaskDiscussionPage:
    """Read one correctly ordered page from both authoritative comment sources."""

    source_selects = _identifier_selects(
        task_id=task.id,
        scope=scope,
        annotation_id=annotation_id,
        project_id=task.project_id,
    )
    identifiers = union_all(*source_selects).subquery("discussion_identifiers")

    total = int(await db.scalar(select(func.count()).select_from(identifiers)) or 0)

    position: DiscussionCursor | None = None
    if cursor is not None:
        position = decode_discussion_cursor(
            cursor,
            task_id=task.id,
            scope=scope,
            annotation_id=annotation_id,
        )

    page_query = select(
        identifiers.c.item_id,
        identifiers.c.created_at,
        identifiers.c.source,
    )
    if position is not None:
        page_query = page_query.where(
            or_(
                identifiers.c.created_at < position.created_at,
                and_(
                    identifiers.c.created_at == position.created_at,
                    identifiers.c.source < position.source,
                ),
                and_(
                    identifiers.c.created_at == position.created_at,
                    identifiers.c.source == position.source,
                    identifiers.c.item_id < position.item_id,
                ),
            )
        )
    page_query = page_query.order_by(
        identifiers.c.created_at.desc(),
        identifiers.c.source.desc(),
        identifiers.c.item_id.desc(),
    ).limit(limit + 1)
    identifier_rows = list((await db.execute(page_query)).all())
    has_next = len(identifier_rows) > limit
    page_identifiers = identifier_rows[:limit]

    next_cursor: str | None = None
    if has_next and page_identifiers:
        last = page_identifiers[-1]
        next_cursor = encode_discussion_cursor(
            task_id=task.id,
            scope=scope,
            annotation_id=annotation_id,
            created_at=last.created_at,
            source=last.source,
            item_id=last.item_id,
        )

    # Hydrate each source once for the page.  In particular, maps are keyed by
    # (source, id), never by id alone, because PostgreSQL UUIDs may coincide across
    # the two source tables.
    annotation_ids = [
        row.item_id for row in page_identifiers if row.source == "annotation_comment"
    ]
    feedback_ids = [row.item_id for row in page_identifiers if row.source == "feedback"]

    annotation_by_id: dict[uuid.UUID, tuple[AnnotationComment, str | None]] = {}
    if annotation_ids:
        annotation_rows = (
            await db.execute(
                select(AnnotationComment, User.name)
                .join(User, User.id == AnnotationComment.author_id)
                .where(AnnotationComment.id.in_(annotation_ids))
            )
        ).all()
        annotation_by_id = {
            comment.id: (comment, name) for comment, name in annotation_rows
        }

    feedback_by_id: dict[uuid.UUID, AnnotationFeedback] = {}
    if feedback_ids:
        feedback_rows = (
            (
                await db.execute(
                    select(AnnotationFeedback).where(
                        AnnotationFeedback.id.in_(feedback_ids)
                    )
                )
            )
            .scalars()
            .all()
        )
        feedback_by_id = {feedback.id: feedback for feedback in feedback_rows}

    feedback_briefs = await resolve_briefs(
        db,
        [feedback.author_id for feedback in feedback_by_id.values()],
    )

    items: list[TaskDiscussionItem] = []
    for row in page_identifiers:
        if row.source == "annotation_comment":
            hydrated = annotation_by_id.get(row.item_id)
            if hydrated is None:  # pragma: no cover - same snapshot guarantees this
                continue
            comment, author_name = hydrated
            data: AnnotationCommentOut | AnnotationFeedbackOut = (
                _annotation_comment_out(comment, author_name)
            )
            actions = _actions_for(
                source="annotation_comment", author_id=comment.author_id, user=user
            )
            source: DiscussionSource = "annotation_comment"
        else:
            feedback = feedback_by_id.get(row.item_id)
            if feedback is None:  # pragma: no cover - same snapshot guarantees this
                continue
            brief = feedback_briefs.get(str(feedback.author_id))
            data = _feedback_out(feedback, brief.name if brief is not None else None)
            actions = _actions_for(
                source="feedback", author_id=feedback.author_id, user=user
            )
            source = "feedback"
        items.append(TaskDiscussionItem(source=source, data=data, actions=actions))

    return TaskDiscussionPage(
        items=items,
        next_cursor=next_cursor,
        total=total,
    )
